### ISSUE TITLE
DATA_PREPARE.md,GET_STARTED.md,INSTALL.md are all empty

### ISSUE THREAD

**Issue by fjl150** [ywyeli/UniDrive#4]
DATA_PREPARE.md,GET_STARTED.md,INSTALL.md are all empty，thus, make it a problem to review merits of the project. Please update.

**Comment by Rushikesh22750** [comment]
Whys is issue closed without solving it?

**Comment by fjl150** [comment]
Not solved. The author didn't reply to this issue for a long time, and I lose my interest on this paper
, so I closed the issue.


| |
范骏隆
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/2/2025 22:09 |
| To | ***@***.***> |
| Cc | ***@***.***>,
State ***@***.***> |
| Subject | Re: [ywyeli/UniDrive] DATA_PREPARE.md,GET_STARTED.md,INSTALL.md are all empty (Issue #4) |

Whys is issue closed without solving it?
